language: cpp
compiler:
  - gcc
  - clang
dist: bionic
cache: ccache

addons:
  apt:
    packages:
    - libwxgtk3.0-dev
    - libboost-thread1.65-dev
    - libboost-system1.65-dev
    - libboost-test1.65-dev
    - libalure-dev
    - cmake
    - libssl-dev
    - gcc-8
    - g++-8

before_script:
# optional dependencies
  - git submodule update --init --recursive
  - cmake -DSPRINGLOBBY_UPDATER:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/tmp .
script:
  - make -j2 -k
  - make -k check
  - make install
notifications:
  irc:
    channels:
      - chat.freenode.net#springlobby
    on_success: change
    on_failure: change

